blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
    path('tag/<str:tag>/', views.TagView.as_view(), name='tag'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField('カテゴリー', max_length=50)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('タグ', max_length=50)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField('タイトル', max_length=50)
    text = models.TextField('テキスト')
    category = models.ForeignKey(
        Category, verbose_name='カテゴリー',
        on_delete=models.PROTECT
    )
    """ Tagモデルと紐づけ """
    tag = models.ManyToManyField(Tag, verbose_name='タグ')
    """ Blogモデル内の要素と紐づけ """
    relation = models.ManyToManyField('self', verbose_name='関連', blank=True, null=True)
    created_at = models.DateField('作成日', auto_now_add=True)
    updated_at = models.DateField('更新日', auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'ブログ'
        verbose_name_plural = 'ブログ'

blog/views.py
from .models import Category, Tag, Blog
from django.views import generic


class IndexView(generic.ListView):
    model = Blog
    template_name = 'blog/index.html'

    def get_queryset(self):
        queryset = Blog.objects.order_by('-id')
        return queryset


class CategoryView(generic.ListView):
    model = Blog
    template_name = 'blog/index.html'

    def get_queryset(self):
        category = Category.objects.get(name=self.kwargs['category'])
        queryset = Blog.objects.order_by('-id').filter(category=category)
        return queryset
    """ アクセスされた値を取得し辞書に格納 """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_key'] = self.kwargs['category']
        return context


class TagView(generic.ListView):
    model = Blog
    template_name = 'blog/index.html'

    def get_queryset(self):
        tag = Tag.objects.get(name=self.kwargs['tag'])
        queryset = Blog.objects.order_by('-id').filter(tag=tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_key'] = self.kwargs['tag']
        return context


class DetailView(generic.DetailView):
    model = Blog
    template_name = 'blog/detail.html'
    context_object_name = 'blog'

blog/templates/base.html
<!doctype html>
<html>

<head>
    <title>Blog</title>
</head>

<body>
    <h1>Blog</h1>
    {% block content %}
    {% endblock %}
</body>

</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ blog.title }}</h1>
<p>{{ blog.updated_at }}</p>
{{ blog.text | safe | linebreaksbr }}
<hr><br>
<a href="{% url 'blog:index' %}">トップページに戻る</a>
<!-- 関連記事の呼び出し -->
<h1>関連項目</h1>
{% if blog.relation.all %}
{% for blog in blog.relation.all %}
<ul>
    <a href="{% url 'blog:detail' blog.pk %}">
        <li>{{ blog }}</li>
    </a>
</ul>
{% endfor %}
{% else %}
<h2>ありません</h2>
{% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'blog:index' %}">
    <p>トップ</p>
</a>
<div>
    <h4>カテゴリー</h4>
    <!-- context.pyのオブジェクトを取得しています。（category_list）-->
    {% for category in category_list %}
    <a href="{% url 'blog:category' category %}">
        <p style='float: left; margin-right: 5px;'>
            {{ category.name }}
        </p>
    </a>
    {% endfor %}
</div><br>
<!-- 上記のfloatスタイルの影響を受けないようにしている。（clear）-->
<h1 style='clear: both;'>一覧</h1><br>
{% if category_key %}
<h3>カテゴリー：{{ category_key }}</h3>
{% endif %}

<!-- タグ用 -->
<div style='clear: both;'>
    <h4>タグ</h4>
    {% for tag in tag_list %}
    <a href="{% url 'blog:tag' tag %}">
        <p style='float: left; margin-right: 5px;'>
            {{ tag.name }}
        </p>
    </a>
    {% endfor %}
</div>
<h1 style=' clear: both;'>一覧</h1><br>
<!-- クラス定義にした場合 -->
<!-- タグ用も追記 -->
{% if category_key %}
<h3>カテゴリー：{{ category_key }}</h3>
{% elif tag_key %}
<h3>タグ: {{ tag_key }}</h3>
{% endif %}
{% for blog in blog_list %}
<ul>
    <li>
        {{ blog.created_at }}
        {{ blog.title }}
        <a href="{% url 'blog:detail' blog.pk %}">詳細</a>
    </li>
</ul>
{% endfor %}
{% endblock %}